### PR TITLE
Guido/23896 psql schema per dataset

### PR DESCRIPTION
**Pull request by gkoller**
## Introduction

This PR supercedes https://github.com/Amsterdam/schema-tools/pull/233

This PR implements https://dev.azure.com/CloudCompetenceCenter/Data%20Diensten/_wiki/wikis/Data-Diensten.wiki/1755/Amsterdam-Schema-Database-wijzigingen with the exception of the copying of data when a new minor version is introduced (last item in the referenced document).

## Features

- Ability to create new datasets in their own DB schema with versioned tables
- Creates updateable views in the public schema for new datasets for backwards compatibility
- Extended the `schema create all` command to be able to work on all datasets. It can now be used, and is recommended, as an alternative for the Django management command `./manage.py import_schemas --create_tables`, that is, for the `--create_tables` part. `import_schemas` on its own is still required for the `dso-api` to "learn" about the datasets it should serve.
- Added `--exclude` option (with the `-x` abbreviation) to `schema create all` to skip certain datasets for when they are broken or concern proxy datasets
- Extend `create sql` cli command with --versioned/no-versioned flag.

## How to use it?

To see this code in action:

### Single dataset

_(This is demonstrated in a short screencast posted in our Slack channel)_

- DROP all `brk` tables from the `public` schema in your `dataservices` database (if any)
- Run `schema create all --db-url postgresql://dataservices:insecure@localhost:5432/dataservices --schema-url ../amsterdam-schema/datasets brk`
- See that:
  - a new DB schema has been created, called `brk`
  - all the tables in that schema have versioned table names without a `brk` prefix, after all, they already live in their own namespace/schema
  - in the `public` schema as many views have been created as tables have been in the `brk` schema. These (updatable) views are basically nothing more than wrapper over the versioned tables in the `brk` schema.

Of course you can use any dataset other than `brk`.

NOTE: the dropping of the existing tables of a given dataset in the `public` schema, for these testing purposes, is necessary. Without it, `schematools` will assume the dataset is a pre-existing one and will **not** create a new DB schema for it. The new functionality in this PR is exclusively for new datasets that do not yet have a presence in the `public` DB schema. 

### Multiple datasets

```console
schema create all --db-url postgresql://dataservices:insecure@localhost:5432/dataservices --exclude corona
```

We're excluding the `corona` dataset as that one is broken; it misses a `crs` property.

## Missing

- No Django code was touched. Hence we should no longer rely on the Django management command to **create** our tables from Jenkins.
- We don't copy over data from one minor version of a table to a newer minor version of that table. This is a potentially expensive process but should be done to realize the vision set out in https://dev.azure.com/CloudCompetenceCenter/Data%20Diensten/_wiki/wikis/Data-Diensten.wiki (see the last section in that document)
- **Please version bump this project after approval en before merge to master.**

## Related PRs:

- https://github.com/Amsterdam/dso-api/pull/452

### CODE REVIEW

**Comment by gkoller** [comment]
As I have no longer write access to Amsterdam/schema-tools I have forked the repo and rebased my original PR on the changes to master that occurred after my original PR was created.

**Comment by jjmurre** [comment]
> As I have no longer write access to [Amsterdam/schema-tools ](https://github.com/Amsterdam/schema-tools/)I have forked the repo and rebased my original PR on the changes to `master` that occurred after my original PR was created.

Wait, aren't you supposed to lazily lie in the sun or do some other relaxing stuff :-)

But, tx for doing the rebase! I am still waiting on a review on another issue and then I can do the merge.

**Comment by gkoller** [comment]
> But, tx for doing the rebase! I am still waiting on a review on another issue and then I can do the merge.

Yeah, I figured that as it can be quite a pain to resolve merge conflicts if one didn't write any of the code, it would be much easier for me to do that instead.

**Review by jjmurre — APPROVED** [review]
LGTM

**Pull request merged**
