### PR TITLE
Replace deprecated django.contrib.postgres.fields.JSONField

### PR DESCRIPTION
**Pull request by lbam**
Booting up dso-api gives a warning about this one.

### CODE REVIEW

**Comment by vdboor** [comment]
I think that also needs to be reflected in the migration files?

**Comment by lbam** [comment]
Not sure, and the makemigration command complains about password authentication failing for user "bag_v11". What would break without it? Unit tests for schema-tools and dso-api run fine and I can still query datasets after autoreload.

**Comment by lbam** [comment]
Also not sure if this is answer the question, but postgres.fields.JSONField is just models.JSONField with a deprecation warning added:

https://github.com/django/django/blob/main/django/contrib/postgres/fields/jsonb.py

**Comment by lbam** [comment]
Got it, added the migration file.

**Review by vdboor — APPROVED** [review]

**Pull request merged**
