### PR TITLE
Extra fixes for PR #169

### PR DESCRIPTION
**Pull request by vdboor**
Some review comments were because GitHub collaped them. This PR provides the fixes.

These changes don't affect DSO-API.

### CODE REVIEW

**Comment by lbam** [comment]
Version bump? Or do we pretend the current version doesn't exist? ;)

**Comment by gkoller** [comment]
Nice that you've picked them up :+1: 

But I see that https://github.com/Amsterdam/schema-tools/pull/169/files#r667952325 was not addressed in the previous PR, nor in this PR.

If this definition:

```python
class HasAllScopesFunc(Protocol):
    def __call__(self, *scopes: str) -> bool: ...
```
Is causing errors elsewhere in your code base, then I suspect the definition is **not** at fault, but the all the code elsewhere. That's the power of type annotations. They have a habit of pointing out issues.

**Review by jjmurre — APPROVED** [review]
LGTM

**Comment by vdboor** [comment]
> Version bump? Or do we pretend the current version doesn't exist? ;)

I only do a version bump on master, so after approval. Otherwise long standing pull requests may reserve unused version numbers.

**Pull request merged**
